# Generated by Kavia Code Generation Agent
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='api_note_title_Idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-updated_at'], name='api_note_updated_desc_Idx'),
        ),
    ]
